### PR TITLE
Fix Titanium 6.0.0 compatibility, minor refactoring, bump to 2.0.1

### LINKED ISSUE #3: Module not work with android 6+
Module brightness not work with android 6, so, I've took the source code of the v1 "com.widbook.brightness" and rebuild it with sdk 5.4.0.

It works, just remember to change the require method to match the module

here it is
http://www.mediafire.com/download/nupmsh0ph56l8sr/com.widbook.brightness-android-1.5.zip

### PR DESCRIPTION
**Pull request by hansemannn**
Hey @adrianopaladini,

having the `apiversion` set to `3` will break the build-process for Titanium SDK 6.0.0+, since iOS should still use the version `2`. Since this is explicitly checked in 6.0.0+, it will now break if specified differently. 

Besides that, I did minor refactoring to the iOS module, updated the formatting of the README and recompiled Android to fix #3.

[com.apaladini.brightness-android-2.0.1.zip](https://github.com/adrianopaladini/brightness/files/784974/com.apaladini.brightness-android-2.0.1.zip)
[com.apaladini.brightness-iphone-2.0.1.zip](https://github.com/adrianopaladini/brightness/files/587754/com.apaladini.brightness-iphone-2.0.1.zip)

Thx! 🚀

### CODE REVIEW

**Comment by PietroGranati** [comment]
I follow the link in your answer and, big thank you! Really! You made my day!

Best regards 
Pietro

**Comment by PietroGranati** [comment]
I've tryed the android version but throw this error:
`[ERROR] :  TiExceptionHandler: (main) [399944,399944] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,399944] - In ti:/module.js:303,2
[ERROR] :  TiExceptionHandler: (main) [0,399944] - Message: Uncaught Error: Requested module not found: com.apaladini.brightness
[ERROR] :  TiExceptionHandler: (main) [1,399945] - Source:  throw new Error("Requested module not found: " + request); // TODO Set 'code' property to 'MODULE_NOT_FOUND' to match Node?`

**Comment by PietroGranati** [comment]
Any news? @hansemannn

**Comment by gkol** [comment]
@PietroGranati @hansemannn 
I noticed that the jar is misspelled, and the following warning is showing up in the logs.

[WARN] :   Module com.apaladini.brightness version 2.0.1 does not have a main jar file

**Comment by hansemannn** [comment]
Sorry @PietroGranati, oversaw it the last months. Let me check it today! 

**EDIT**: Try this one: [com.apaladini.brightness-android-2.0.1.zip](https://github.com/adrianopaladini/brightness/files/784974/com.apaladini.brightness-android-2.0.1.zip)

**Comment by hansemannn** [comment]
@adrianopaladini Can we get this in? Thanks!

**Comment by PietroGranati** [comment]
Thank you @hansemannn

**Comment by hansemannn** [comment]
Ping, @adrianopaladini! 😊 Using it in some of my production apps since a while already.

**Pull request closed without merging**
